name: HandleIssue

on:
  issues:
    types:
      - opened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for creating your first issue on this repo.'

    - name: initial labeling
      uses: andymckay/labeler@master
      with:
        add-labels: "triage"
        remove-labels: "in progress"