name: CalcLibWorkflow

on:
  push:
    branches: [ main ]
    paths:
      - 'src/Calculator/**'
      - '.github/workflows/calc-lib.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/Calculator/**'
      - '.github/workflows/calc-lib.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/Calculator/Calculator.sln
    - name: Build
      run: dotnet build --no-restore src/Calculator/Calculator.sln
    - name: Test
      run: dotnet test --no-build src/Calculator/Calculator.sln --verbosity normal --logger "trx;LogFileName=test-results.trx"
      
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: CalcLib Tests
        path: '**/TestResults/*.trx'
        reporter: dotnet-trx
